version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
            --template-file template.yml \
            --stack-name kelly-${CIRCLE_WORKFLOW_ID:0:5}

  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: install ansible 
          command: |
            apk add --update ansible
      - run:
          name: configure instance
          command: |
            ansible-playbook -i inventory.txt main.yml

  smoke-test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apk add --update curl
      - run: 
          name: smoke test
          command: |
            URL="https://blog.udacity.com/"
            # Test if website exists
            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi



workflows:
  run-workflow:
    jobs:
      # - create-infrastructure
      # - configure-infrastructure
      - smoke-test